name: gemini-video-api
region: nyc
services:
  - build_command: npm run build
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: GOOGLE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PORT
        scope: RUN_TIME
        value: "8080"
    github:
      branch: main
      deploy_on_push: true
      repo: yourusername/gemini-video-recognition
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    name: api
    routes:
      - path: /
    run_command: npm start
    source_dir: /
